# Generated by Django 4.2.29 on 2026-04-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('engine', 'Двигатель'), ('transmission', 'Трансмиссия'), ('brakes', 'Тормозная система'), ('suspension', 'Подвеска'), ('electrics', 'Электрика'), ('body', 'Кузовные детали'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('compatibility', models.CharField(blank=True, max_length=200, verbose_name='Совместимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'ordering': ['-created_at'],
            },
        ),
    ]
