# Generated by Django 4.2.29 on 2026-05-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_order_paid_order_payment_id_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными при получении'), ('card', 'Банковской картой онлайн')], default='cash', max_length=20),
        ),
    ]
